name: project_manag_ite
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  jiffy: ^6.3.2
  intl: ^0.19.0
  http: ^1.2.0
  cached_network_image: ^3.3.1
  image_picker: ^1.0.8
  image_pickers: ^2.0.6
  path_provider: ^2.1.4
  open_filex: ^4.4.0
  show_up_animation: ^2.1.0
  auto_animated: ^3.2.0
  firebase_core: ^2.27.0
  firebase_messaging: ^14.7.19
  cloud_firestore: ^4.15.8
  flutter_local_notifications: ^18.0.1
  shared_preferences: ^2.2.3
  path: ^1.8.3
  grouped_list: ^6.0.0
  url_launcher: ^6.3.0
  dropdown_search: ^6.0.2
  badges: ^3.1.2
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.8.0
  fluttericon: ^2.0.0
  dartz: ^0.10.1
  google_sign_in: ^6.2.1
  get: ^4.6.6
  smooth_page_indicator: ^1.2.1
  flutter_otp_text_field: ^1.5.1+1
  pin_code_fields: ^8.0.1
  lottie: ^3.1.3
  carousel_slider: ^5.1.1
  google_nav_bar: ^5.0.7
  flutter_screenutil: ^5.9.3
  shimmer: ^3.0.0
  permission_handler: ^11.3.1
  file_picker: ^8.0.0+1
  date_format: ^2.0.9
  pusher_channels_flutter: ^2.5.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/dark/
    - assets/images/light/
    - assets/icons/
    - assets/fonts/
    - assets/lottie/ 
    - assets/gif/ 

  fonts:
    - family: Hekaya
      fonts:
        - asset: assets/fonts/FFHekaya-Light.otf
          weight: 700

# إعدادات الأيقونة
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/app_icon.png"
